// Ticket 2.1 — canonical keep-list of indexable STATE + CITY destination pages.
//
// Continents (1 path segment) and countries (2 segments) are ALWAYS indexable.
// States (3 segments) and cities (4 segments) are indexable only if their path
// appears below. Every state/city NOT listed is served with
// <meta name="robots" content="noindex,follow"> and dropped from the sitemap.
//
// Reversible by design (ticket 2.1 rule 4): to promote a page, add its path
// here — no content is deleted. Paths are stored WITHOUT a leading slash to
// match the CMS `path` field; isDestinationIndexable() normalises either form.
//
// Built from 12-month GSC clicks + outbound commercial corridors. Regenerate/
// extend from docs/seo/destination-inventory.md.

// ── Tier B — India states (21) ──────────────────────────────────────────────
const INDIA_STATES = [
  "asia/india/andaman_and_nicobar",
  "asia/india/andhra_pradesh",
  "asia/india/arunachal_pradesh",
  "asia/india/bihar",
  "asia/india/chhattisgarh",
  "asia/india/delhi",
  "asia/india/goa",
  "asia/india/gujarat",
  "asia/india/himachal_pradesh",
  "asia/india/jammu_and_kashmir",
  "asia/india/jharkhand",
  "asia/india/karnataka",
  "asia/india/kerala",
  "asia/india/ladakh",
  "asia/india/maharashtra",
  "asia/india/meghalaya",
  "asia/india/nagaland",
  "asia/india/rajasthan",
  "asia/india/tamil_nadu",
  "asia/india/uttar_pradesh",
  "asia/india/uttarakhand",
];

// ── Tier B — India cities (202) ─────────────────────────────────────────────
const INDIA_CITIES = [
  "asia/india/andhra_pradesh/dwaraka_tirumala",
  "asia/india/andhra_pradesh/horsley_hills",
  "asia/india/andhra_pradesh/puttaparthi",
  "asia/india/andhra_pradesh/srisailam",
  "asia/india/andhra_pradesh/tuni",
  "asia/india/andhra_pradesh/vijayawada",
  "asia/india/arunachal_pradesh/anini",
  "asia/india/arunachal_pradesh/namsai",
  "asia/india/arunachal_pradesh/ziro",
  "asia/india/assam/dibrugarh",
  "asia/india/assam/guwahati",
  "asia/india/assam/harmuti",
  "asia/india/assam/silchar",
  "asia/india/assam/sivasagar",
  "asia/india/bihar/patna",
  "asia/india/bihar/rajgir",
  "asia/india/bihar/sasaram",
  "asia/india/chandigarh/chandigarh",
  "asia/india/chhattisgarh/ambikapur",
  "asia/india/chhattisgarh/jagdalpur",
  "asia/india/chhattisgarh/jashpur",
  "asia/india/chhattisgarh/kawardha",
  "asia/india/chhattisgarh/korba",
  "asia/india/chhattisgarh/raipur",
  "asia/india/chhattisgarh/rajnandgaon",
  "asia/india/dadra_and_nagar_haveli_and_daman_and_diu/daman",
  "asia/india/dadra_and_nagar_haveli_and_daman_and_diu/khanvel",
  "asia/india/dadra_and_nagar_haveli_and_daman_and_diu/silvassa",
  "asia/india/goa/south_goa",
  "asia/india/gujarat/bhuj",
  "asia/india/gujarat/champaner",
  "asia/india/gujarat/dasada",
  "asia/india/gujarat/dwarka",
  "asia/india/gujarat/junagadh",
  "asia/india/gujarat/rajkot",
  "asia/india/gujarat/saputara",
  "asia/india/gujarat/somnath",
  "asia/india/gujarat/surat",
  "asia/india/gujarat/vadodara",
  "asia/india/haryana/charkhi_dadri",
  "asia/india/haryana/faridabad",
  "asia/india/haryana/fatehabad",
  "asia/india/haryana/kurukshetra",
  "asia/india/haryana/panchkula",
  "asia/india/himachal_pradesh/batal_village",
  "asia/india/himachal_pradesh/chandratal",
  "asia/india/himachal_pradesh/fagu",
  "asia/india/himachal_pradesh/gushaini",
  "asia/india/himachal_pradesh/jibhi",
  "asia/india/himachal_pradesh/kalpa",
  "asia/india/himachal_pradesh/kasol",
  "asia/india/himachal_pradesh/mandi",
  "asia/india/himachal_pradesh/mashobra",
  "asia/india/himachal_pradesh/pulga",
  "asia/india/himachal_pradesh/rampur",
  "asia/india/himachal_pradesh/shoghi",
  "asia/india/himachal_pradesh/shoja",
  "asia/india/himachal_pradesh/solan",
  "asia/india/jammu_and_kashmir/dachigam_national_park",
  "asia/india/jammu_and_kashmir/sonamarg",
  "asia/india/jharkhand/chaibasa",
  "asia/india/jharkhand/jamshedpur",
  "asia/india/jharkhand/madhupur",
  "asia/india/jharkhand/netarhat",
  "asia/india/jharkhand/sahibganj",
  "asia/india/karnataka/agumbe",
  "asia/india/karnataka/bengaluru",
  "asia/india/karnataka/chikmagalur",
  "asia/india/karnataka/gokarna",
  "asia/india/karnataka/hassan",
  "asia/india/karnataka/madikeri",
  "asia/india/karnataka/mangalore",
  "asia/india/karnataka/sakleshpur",
  "asia/india/karnataka/shimoga",
  "asia/india/karnataka/shravanabelagola",
  "asia/india/karnataka/udupi",
  "asia/india/karnataka/yana",
  "asia/india/kerala/attappadi",
  "asia/india/kerala/bekal",
  "asia/india/kerala/gavi",
  "asia/india/kerala/guruvayur",
  "asia/india/kerala/kattappana",
  "asia/india/kerala/kochi",
  "asia/india/kerala/kodanad",
  "asia/india/kerala/kozhikode",
  "asia/india/kerala/malappuram",
  "asia/india/kerala/mundakayam",
  "asia/india/kerala/munnar",
  "asia/india/kerala/nelliyampathy",
  "asia/india/kerala/nilambur",
  "asia/india/kerala/ponmudi",
  "asia/india/kerala/ponnani",
  "asia/india/kerala/sabarimala",
  "asia/india/kerala/thekkady",
  "asia/india/kerala/thrissur",
  "asia/india/kerala/vagamon",
  "asia/india/kerala/varkala",
  "asia/india/kerala/wayanad",
  "asia/india/ladakh/chumathang",
  "asia/india/ladakh/hanle",
  "asia/india/ladakh/sumur",
  "asia/india/madhya_pradesh/amarkantak",
  "asia/india/madhya_pradesh/bhedaghat",
  "asia/india/madhya_pradesh/bhopal",
  "asia/india/madhya_pradesh/gwalior",
  "asia/india/madhya_pradesh/indore",
  "asia/india/madhya_pradesh/shivpuri",
  "asia/india/madhya_pradesh/ujjain",
  "asia/india/maharashtra/bhandardara",
  "asia/india/maharashtra/bhimashankar",
  "asia/india/maharashtra/diveagar",
  "asia/india/maharashtra/ganpatipule",
  "asia/india/maharashtra/harihareshwar",
  "asia/india/maharashtra/kamshet",
  "asia/india/maharashtra/kolad",
  "asia/india/maharashtra/lonavala",
  "asia/india/maharashtra/mahabaleshwar",
  "asia/india/maharashtra/matheran",
  "asia/india/maharashtra/mumbai",
  "asia/india/maharashtra/nagpur",
  "asia/india/maharashtra/nanded",
  "asia/india/maharashtra/nashik",
  "asia/india/maharashtra/ratnagiri",
  "asia/india/manipur/ukhrul",
  "asia/india/meghalaya/jaintia_hills",
  "asia/india/meghalaya/jowai",
  "asia/india/meghalaya/mawphlang",
  "asia/india/meghalaya/nongjrong",
  "asia/india/odisha/koraput",
  "asia/india/odisha/sambalpur",
  "asia/india/pondicherry/pondicherry",
  "asia/india/punjab/anandpur_sahib",
  "asia/india/punjab/bathinda",
  "asia/india/punjab/kapurthala",
  "asia/india/punjab/mohali",
  "asia/india/rajasthan/barmer",
  "asia/india/rajasthan/chittorgarh",
  "asia/india/rajasthan/jaipur",
  "asia/india/rajasthan/jaisalmer",
  "asia/india/rajasthan/khimsar",
  "asia/india/rajasthan/kumbhalgarh",
  "asia/india/rajasthan/nathdwara",
  "asia/india/rajasthan/nawalgarh",
  "asia/india/rajasthan/neemrana",
  "asia/india/rajasthan/osian",
  "asia/india/rajasthan/pilani",
  "asia/india/rajasthan/pushkar",
  "asia/india/rajasthan/rajsamand",
  "asia/india/sikkim/yuksom",
  "asia/india/tamil_nadu/chennai",
  "asia/india/tamil_nadu/madurai",
  "asia/india/tamil_nadu/ooty",
  "asia/india/tamil_nadu/salem",
  "asia/india/tamil_nadu/thanjavur",
  "asia/india/tamil_nadu/theni",
  "asia/india/tamil_nadu/thiruvannamalai",
  "asia/india/tamil_nadu/tirunelveli",
  "asia/india/tamil_nadu/tranquebar",
  "asia/india/tamil_nadu/tuticorin",
  "asia/india/tamil_nadu/valparai",
  "asia/india/tamil_nadu/velankanni",
  "asia/india/tamil_nadu/vellore",
  "asia/india/tamil_nadu/yercaud",
  "asia/india/telangana/bhadrachalam",
  "asia/india/telangana/hyderabad",
  "asia/india/telangana/karimnagar",
  "asia/india/telangana/yadagirigutta",
  "asia/india/tripura/belonia",
  "asia/india/tripura/sabroom",
  "asia/india/tripura/udaipur",
  "asia/india/uttar_pradesh/ayodhya",
  "asia/india/uttar_pradesh/chitrakoot",
  "asia/india/uttar_pradesh/gorakhpur",
  "asia/india/uttar_pradesh/lucknow",
  "asia/india/uttar_pradesh/mirzapur",
  "asia/india/uttar_pradesh/noida",
  "asia/india/uttar_pradesh/varanasi",
  "asia/india/uttar_pradesh/vrindavan",
  "asia/india/uttarakhand/baijnath",
  "asia/india/uttarakhand/barsu",
  "asia/india/uttarakhand/chakrata",
  "asia/india/uttarakhand/chamoli",
  "asia/india/uttarakhand/dehradun",
  "asia/india/uttarakhand/dhanachuli",
  "asia/india/uttarakhand/dhanaulti",
  "asia/india/uttarakhand/haridwar",
  "asia/india/uttarakhand/jageshwar",
  "asia/india/uttarakhand/kainchi_dham",
  "asia/india/uttarakhand/kedarnath",
  "asia/india/uttarakhand/lansdowne",
  "asia/india/uttarakhand/nainital",
  "asia/india/uttarakhand/naukuchiatal",
  "asia/india/uttarakhand/pangot",
  "asia/india/uttarakhand/peora",
  "asia/india/uttarakhand/rishikesh",
  "asia/india/uttarakhand/tehri_garhwal",
  "asia/india/west_bengal/bishnupur",
  "asia/india/west_bengal/howrah",
  "asia/india/west_bengal/mandarmani",
  "asia/india/west_bengal/nabadwip",
  "asia/india/west_bengal/siliguri",
  "asia/india/west_bengal/tarapith",
];

// ── Tier C — Outbound commercial cities/states (47) ─────────────────────────
const OUTBOUND = [
  "africa/egypt/cairo_governorate/cairo",
  "africa/kenya/baringo/nairobi",
  "asia/bhutan/chhukha_dzongkhag",
  "asia/hong_kong",
  "asia/indonesia/bali/kuta",
  "asia/indonesia/bali/ubud",
  "asia/japan/kyoto",
  "asia/japan/osaka",
  "asia/japan/tokyo",
  "asia/kazakhstan/almaty_region/almaty",
  "asia/malaysia/kedah/langkawi",
  "asia/malaysia/kuala_lumpur",
  "asia/malaysia/kuala_lumpur/genting_highlands",
  "asia/malaysia/penang",
  "asia/nepal/mustang",
  "asia/south_korea/seoul",
  "asia/sri_lanka/western_province",
  "asia/thailand/bangkok/bangkok",
  "asia/thailand/chonburi/pattaya",
  "asia/thailand/krabi",
  "asia/thailand/phuket_province/phuket",
  "asia/united_arab_emirates/abu_dhabi",
  "asia/united_arab_emirates/dubai",
  "asia/vietnam/da_nang",
  "asia/vietnam/hanoi",
  "asia/vietnam/ho_chi_minh_city",
  "asia/vietnam/quang_nam/hoi_an",
  "europe/austria/vienna_region/vienna",
  "europe/czech_republic/bohemia/prague",
  "europe/france/ile-de-france/paris",
  "europe/greece/attica/athens",
  "europe/greece/south_aegean/santorini",
  "europe/hungary/budapest",
  "europe/italy/lazio/rome",
  "europe/italy/lombardy/milan",
  "europe/italy/tuscany/florence",
  "europe/italy/veneto/venice",
  "europe/netherlands/north_holland_province/amsterdam",
  "europe/portugal/central_portugal/lisbon",
  "europe/spain/catalonia/barcelona",
  "europe/spain/madrid",
  "europe/switzerland/canton_of_bern/interlaken",
  "europe/switzerland/canton_of_lucerne/lucerne",
  "europe/switzerland/canton_of_zurich",
  "europe/united_kingdom/england/london",
  "oceania/australia/new_south_wales/sydney",
  "oceania/australia/victoria/melbourne",
];

const KEEP = new Set([...INDIA_STATES, ...INDIA_CITIES, ...OUTBOUND]);

function normalizePath(p) {
  return String(p || "").replace(/^\/+/, "").replace(/\/+$/, "");
}

// Continents (<=2 segments including country) are always indexable; states and
// cities (3–4 segments) only if present in the keep-list.
function isDestinationIndexable(path) {
  const p = normalizePath(path);
  if (!p) return true;
  const depth = p.split("/").length;
  if (depth <= 2) return true; // continent or country
  return KEEP.has(p);
}

module.exports = {
  isDestinationIndexable,
  normalizePath,
  KEEP_DESTINATION_PATHS: KEEP,
};
