export const AUTH_STARTLOADING = "AUTH_STARTLOADING";
export const AUTH_STARTLOADINGSOCIAL = "AUTH_STARTLOADINGSOCIAL";
export const AUTH_STOPLOADINGSOCIAL = "AUTH_STOPLOADINGSOCIAL";

export const AUTH_SETLOGINMESSAGE = "AUTH_SETLOGINMESSAGE";
export const AUTH_HIDELOGINCLOSE = "AUTH_HIDELOGINCLOSE";

export const AUTH_SHOWLOGIN = "AUTH_SHOWLOGIN";
export const AUTH_CLOSELOGIN = "AUTH_CLOSELOGIN";
export const AUTH_RESETLOGIN = "AUTH_RESETLOGIN";

export const AUTH_STOPLOADING = "AUTH_STOPLOADING";

export const AUTH_OTPSENT = "AUTH_OTPSENT";
export const AUTH_MOBILEFAIL = "AUTH_MOBILEFAIL";
export const AUTH_OTPFAIL = "AUTH_OTPFAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const NEW_USER = "NEW_USER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_EMAILFAIL = "AUTH_EMAILFAIL";
export const AUTH_RESETEMAIL = "AUTH_RESETEMAIL";
export const AUTH_RESETOTPFAIL = "AUTH_RESETOTPFAIL";
export const AUTH_CHECKAUTHCOMPLETED = "AUTH_CHECKAUTHCOMPLETED";
export const AUTH_SETAUTHREDIRECT = "AUTH_SETAUTHREDIRECT";
export const AUTH_SETUSERDETAILS = "AUTH_SETUSERDETAILS";
export const AUTH_SETPROFILE_PIC = "AUTH_SETPROFILE_PIC";
export const ORDER_SETORDERDETAILS = "ORDER_SETORDERDETAILS";
export const ORDER_SETSALEID = "ORDER_SETSALEID";
export const ORDER_CREATIONSTARTED = "ORDER_CREATIONSTARTED";
export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_PLACED = "ORDER_PLACED";
export const ORDER_COUPONAPPLIED = "ORDER_COUPONAPPLIED";
export const ORDER_COUPONAINVALID = "ORDER_COUPONAINVALID";
export const SET_UPDATE_LOADING = "SET_UPDATE_LOADING";
export const SET_ACTIVE_COMPONENT = "SET_ACTIVE_COMPONENT";
export const NOTIFICATION_OPEN = "NOTIFICATION_OPEN";
export const NOTIFICATION_CLOSE = "NOTIFICATION_CLOSE";
export const SCROLL_CHANGE = "SCROLL_CHANGE";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_ITINERARY_START_DATE = "SET_ITINERARY_START_DATE";
export const SET_ITINERARY_ACTIVITIES = "SET_ITINERARY_ACTIVITIES";
export const SET_ITINERARY_ID = "SET_ITINERARY_ID";
export const SET_ITINERARY_ROUTES = "SET_ITINERARY_ROUTES";
export const SET_ITINERARY = "SET_ITINERARY";
export const SET_PLAN = "SET_PLAN";
