import React from "react";

type Variant = "light" | "dark";

/**
 * Logo assets are generated by scripts/logo/gen_logo.py and shipped under
 * /public/logo. The lockup is composed from PARTS here (mark + wordmark +
 * tagline) rather than using the single ttw-lockup*.svg, so the tagline can be
 * sized independently of the logo.
 *
 * Why: baked into the lockup the tagline scales with the logo and, at the
 * 32-40px the logo renders in nav/header/sidebar, collapses to an unreadable
 * ~3px smudge. Composing it separately lets us floor its height (see `taglineH`)
 * so "AI Trip Planner" stays legible even on a small logo. Below `taglineMinSize`
 * it is dropped entirely (clean mark+wordmark).
 */
const ASSETS: Record<Variant, { mark: string; wordmark: string; tagline: string }> = {
  light: {
    mark: "/logo/ttw-mark.svg",
    wordmark: "/logo/ttw-wordmark.svg",
    tagline: "/logo/ttw-tagline.svg",
  },
  dark: {
    mark: "/logo/ttw-mark-light.svg",
    wordmark: "/logo/ttw-wordmark-light.svg",
    tagline: "/logo/ttw-tagline-light.svg",
  },
};

// Aspect ratios (width / height) of the wordmark and tagline artboards, taken
// from their viewBoxes in scripts/logo/gen_logo.py. Keep in sync if the
// artboards change (ttw-wordmark: 359x82, ttw-tagline "• AI TRIP PLANNER": 132x9).
const WORDMARK_AR = 359 / 82;
const TAGLINE_AR = 132 / 9;

// Floor for the tagline height (px): below this "AI Trip Planner" stops being
// legible. On small logos the tagline renders at this floor rather than shrinking
// with the mark, so it stays readable. It is still hard-capped to the wordmark
// width below (see `taglineW`), so it can never overhang the line above it.
const TAGLINE_MIN_H = 6.5;

export interface BrandLockupProps {
  /** Tile (mark) height in px — the logo's visual size. */
  size?: number;
  /** "light" = light background (navy wordmark); "dark" = dark background (cream). */
  variant?: Variant;
  /**
   * Show the "AI Trip Planner" line.
   *  - "auto" (default): shown when `size >= taglineMinSize`.
   *  - true / false: force on / off.
   */
  tagline?: boolean | "auto";
  /**
   * Min `size` at which "auto" reveals the tagline. Default 0 — the tagline is
   * shown at every size (it's floored for legibility). Raise it on a surface
   * that should fall back to the clean mark+wordmark.
   */
  taglineMinSize?: number;
  /**
   * Render only the mark (no wordmark/tagline) — the compact "mobile logo".
   * Use on narrow surfaces where the full wordmark would overflow the row.
   */
  markOnly?: boolean;
  className?: string;
  style?: React.CSSProperties;
  onClick?: React.MouseEventHandler<HTMLElement>;
  /** Accessible name for the whole lockup. */
  alt?: string;
}

/**
 * The Tarzan Way brand lockup. Proportions match the design at tile=114:
 * gap 30, wordmark 77.4, tagline row below the wordmark — scaled by `size`.
 */
export default function BrandLockup({
  size = 40,
  variant = "light",
  tagline = "auto",
  taglineMinSize = 0,
  markOnly = false,
  className,
  style,
  onClick,
  alt = "The Tarzan Way",
}: BrandLockupProps) {
  const a = ASSETS[variant] ?? ASSETS.light;
  const showTagline =
    tagline === true || (tagline === "auto" && size >= taglineMinSize);

  const gap = 0.17 * size; // mark -> text column
  const wordmarkH = 0.66 * size; // wordmark height
  const wordmarkW = wordmarkH * WORDMARK_AR;
  const colGap = Math.max(3, 0.09 * size); // wordmark -> tagline

  // Vertical alignment: the wordmark+tagline column is centered as a group on the
  // tile (equal margin above the wordmark and below the tagline). `img { margin }`
  // from global/Bootstrap resets would break this, so every image below zeroes its
  // margin explicitly — without that the phantom margin skews the flex centering.
  const imgReset = { margin: 0, maxWidth: "none" as const };

  // ...then lift the whole block a hair above dead-centre — optically it reads as
  // balanced against the tile's visual weight (kept small so it never rises past
  // the tile top, even at the smallest logo sizes).
  const textRise = 0.03 * size;

  // Tagline: floored for legibility, then hard-capped to the wordmark width so it
  // never overhangs the line above. When the cap bites, height scales down with
  // the width (AR preserved) rather than the line getting clipped or stretched.
  const taglineH0 = Math.max(TAGLINE_MIN_H, 0.074 * size);
  const taglineW = Math.min(taglineH0 * TAGLINE_AR, wordmarkW);
  const taglineH = taglineW / TAGLINE_AR;

  return (
    <span
      className={className}
      onClick={onClick}
      role="img"
      aria-label={alt}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap,
        lineHeight: 0,
        ...style,
      }}
    >
      <img
        src={a.mark}
        alt=""
        aria-hidden
        style={{ height: size, width: size, display: "block", flex: "none", ...imgReset }}
      />
      {!markOnly && (
      <span
        style={{
          display: "inline-flex",
          flexDirection: "column",
          gap: colGap,
          transform: `translateY(${-textRise}px)`,
        }}
      >
        <img
          src={a.wordmark}
          alt=""
          aria-hidden
          style={{
            height: wordmarkH,
            width: wordmarkW,
            display: "block",
            ...imgReset,
          }}
        />
        {showTagline && (
          <img
            src={a.tagline}
            alt=""
            aria-hidden
            style={{
              height: taglineH,
              width: taglineW,
              display: "block",
              ...imgReset,
            }}
          />
        )}
      </span>
      )}
    </span>
  );
}
